// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB192rklslwZrd5SCa8Jh6JKaT79DgwtlM',
    appId: '1:163422970956:web:bc55c70235b0f4fb5e40e9',
    messagingSenderId: '163422970956',
    projectId: 'productivity-ed374',
    authDomain: 'productivity-ed374.firebaseapp.com',
    databaseURL: 'https://productivity-ed374-default-rtdb.firebaseio.com',
    storageBucket: 'productivity-ed374.firebasestorage.app',
    measurementId: 'G-P23QESFEVE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArhJtRDTUdSl5mn-WTwCNCToC3PaHQQBM',
    appId: '1:163422970956:android:b4474aa16087d0355e40e9',
    messagingSenderId: '163422970956',
    projectId: 'productivity-ed374',
    databaseURL: 'https://productivity-ed374-default-rtdb.firebaseio.com',
    storageBucket: 'productivity-ed374.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOc_vJicUG1JpCEJhFmPlzYg02Ek0WZp0',
    appId: '1:163422970956:ios:a3ccb46e9a83fc415e40e9',
    messagingSenderId: '163422970956',
    projectId: 'productivity-ed374',
    databaseURL: 'https://productivity-ed374-default-rtdb.firebaseio.com',
    storageBucket: 'productivity-ed374.firebasestorage.app',
    androidClientId: '163422970956-ghbsk673ftvje7jj2a2tulaqsrc0ouo7.apps.googleusercontent.com',
    iosClientId: '163422970956-6785dcs1j0aerm7d3ijp33f60pv6v79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOc_vJicUG1JpCEJhFmPlzYg02Ek0WZp0',
    appId: '1:163422970956:ios:a3ccb46e9a83fc415e40e9',
    messagingSenderId: '163422970956',
    projectId: 'productivity-ed374',
    databaseURL: 'https://productivity-ed374-default-rtdb.firebaseio.com',
    storageBucket: 'productivity-ed374.firebasestorage.app',
    androidClientId: '163422970956-ghbsk673ftvje7jj2a2tulaqsrc0ouo7.apps.googleusercontent.com',
    iosClientId: '163422970956-6785dcs1j0aerm7d3ijp33f60pv6v79c.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB192rklslwZrd5SCa8Jh6JKaT79DgwtlM',
    appId: '1:163422970956:web:fe4524f1d58080af5e40e9',
    messagingSenderId: '163422970956',
    projectId: 'productivity-ed374',
    authDomain: 'productivity-ed374.firebaseapp.com',
    databaseURL: 'https://productivity-ed374-default-rtdb.firebaseio.com',
    storageBucket: 'productivity-ed374.firebasestorage.app',
    measurementId: 'G-R9CJPSPV99',
  );
}
